const movies = [
  {
    "Title": "Patton Oswalt: Annihilation",
    "fulltitle": "Patton Oswalt: Annihilation (2017)",
    "movie_year": 2017,
    "Categories": "Uncategorized",
    "summary": "Patton Oswald, despite a personal tragedy, produces his best standup yet. Focusing on the tribulations of the Trump era and life after the loss of a loved one, Patton Oswald continues his journey to contribute joy to the world.",
    "ImageURL": "https://www.theringer.com/_next/image?url=https%3A%2F%2Fwp.theringer.com%2Fwp-content%2Fuploads%2F2017%2F10%2FPOCS_Unit_00088_R-scaled.jpg&w=3840&q=75&dpl=36e1450c8a410817cd7405f624f11e56b9c206fc",
    "imdb_id": "tt7026230",
    "imdb_rating": 7.4,
    "runtime": 66,
    "language": "English",
    "ytid": "4hZi5QaMBFc"
  },
  {
    "Title": "New York Doll",
    "fulltitle": "New York Doll (2005)",
    "movie_year": 2005,
    "Categories": "Documentary|Music",
    "summary": "A recovering alcoholic and recently converted Mormon, Arthur \"Killer\" Kane, of the rock band The New York Dolls, is given a chance at reuniting with his band after 30 years.",
    "ImageURL": "https://media.pitchfork.com/photos/67eae0ddf07c6a7c49d37815/16:9/w_1280,c_limit/New%20York%20Dolls:%20New%20York%20Dolls.jpg",
    "imdb_id": "tt0436629",
    "imdb_rating": 7.9,
    "runtime": 75,
    "language": "English",
    "ytid": "jwD04NsnLLg"
  },
  {
    "Title": "Mickey's Magical Christmas: Snowed in at the House of Mouse",
    "fulltitle": "Mickey's Magical Christmas: Snowed in at the House of Mouse (2001)",
    "movie_year": 2001,
    "Categories": "Adventure|Animation|Comedy|Family|Fantasy",
    "summary": "After everyone is snowed in at the House of Mouse, Mickey suggests they throw their own Christmas party. Everyone is happy, except for Donald who just isn't in to the Christmas spirit. So Mickey shows a series of cartoons that show just what Christmas is all about. It features a star studded cast of Disney characters from everyone's favorite animated Disney movies.",
    "ImageURL": "https://ntvb.tmsimg.com/assets/p441824_b_h10_bi.jpg?w=1280&h=720",
    "imdb_id": "tt0300195",
    "imdb_rating": 6.8,
    "runtime": 65,
    "language": "English",
    "ytid": "uCKwHHftrU4"
  },
  {
    "Title": "Mickey's House of Villains",
    "fulltitle": "Mickey's House of Villains (2001)",
    "movie_year": 2001,
    "Categories": "Animation|Comedy|Family|Fantasy|Horror",
    "summary": "The villains from the popular animated Disney films are gathered at the House of Mouse with plans to take over. Soon, the villains take over the house and kick out Mickey, Donald and Goofy. It's all up to Mickey and his friends to overthrow evil and return the House of Mouse to normal--or as close to normal as it get's.",
    "ImageURL": "https://images.mubicdn.net/images/film/53901/cache-119202-1745492510/image-w1280.jpg?size=800x",
    "imdb_id": "tt0329374",
    "imdb_rating": 6.6,
    "runtime": 0,
    "language": "English",
    "ytid": "JA03ciYt-Ek"
  },
  {
    "Title": "And Then I Go",
    "fulltitle": "And Then I Go (2017)",
    "movie_year": 2017,
    "Categories": "Drama",
    "summary": "In the cruel world of junior high, Edwin suffers in a state of anxiety and alienation alongside his only friend, Flake. Misunderstood by their families and demoralized at school daily, their fury simmers quietly until an idea for vengeance offers them a terrifying release. Based on the acclaimed novel \"Project X\" by Jim Shepard, this unflinching look at adolescence explores how the powerful bonds of childhood friendship and search for belonging can become a matter of life or death.",
    "ImageURL": "https://ew.com/thmb/Nu9tH49cIYyEfkyEDrkww2yllZM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/anthenigo-2000-14c3bf58cf7d44f4a8c2dd558cfa4783.jpg",
    "imdb_id": "tt2018111",
    "imdb_rating": 7.6,
    "runtime": 99,
    "language": "English",
    "ytid": "8CdIiD6-iF0"
  },
  {
    "Title": "An Extremely Goofy Movie",
    "fulltitle": "An Extremely Goofy Movie (2000)",
    "movie_year": 2000,
    "Categories": "Animation|Comedy|Family|Sport",
    "summary": "It's a big time in Max's life. He's college bound with his friends and finally free of his embarrassing father as he strives to be a top contender for the X-Games. Unfortunately, Goofy loses his job and learns that he cannot get another job without a college degree. To his son's mortification, Goofy decides to join him in his campus to get that degree. Desperate to distract his father, Max talks him into joining the competing Gamma Fraternity team and introduces him to a wonderful librarian who shares his nostalgic love for 1970's pastimes. Unfortunately, things do not go according to plan as events put this father-son relationship to the test.",
    "ImageURL": "https://m.media-amazon.com/images/M/MV5BM2U0ODg5NzMtMzNhYy00OGRjLTg4OWEtODlhZWFiMjA3MzI3XkEyXkFqcGc@._V1_.jpg",
    "imdb_id": "tt0208185",
    "imdb_rating": 6.4,
    "runtime": 79,
    "language": "English",
    "ytid": "H8oSvldAGfg"
  },
  {
    "Title": "Peter Rabbit",
    "fulltitle": "Peter Rabbit (2018)",
    "movie_year": 2018,
    "Categories": "Adventure|Animation|Comedy|Family|Fantasy",
    "summary": "Based on the books by Beatrix Potter: Peter Rabbit (James Corden;) his three sisters: Flopsy (Margot Robbie,) Mopsy (Elizabeth Debicki) and Cotton Tail (Daisy Ridley) and their cousin Benjamin (Colin Moody) enjoy their days harassing Mr McGregor in his vegetable garden. Until one day he dies and no one can stop them roaming across his house and lands for a full day or so. However, when one of Mr McGregor's relatives inherits the house and goes to check it out, he finds much more than he bargained for. What ensues, is a battle of wills between the new Mr McGregor and the rabbits. But when he starts to fall in love with Bea (Rose Byrne,) a real lover of all nature, his feelings towards them begin to change. But is it too late?",
    "ImageURL": "https://cdn.iview.abc.net.au/thumbs/1200/zx/ZX9090A54f79409edc5d6.97730748_1280.jpg",
    "imdb_id": "tt5117670",
    "imdb_rating": 6.6,
    "runtime": 95,
    "language": "English",
    "ytid": "7Pa_Weidt08"
  },
  {
    "Title": "Love Songs",
    "fulltitle": "Love Songs (2007)",
    "movie_year": 2007,
    "Categories": "Uncategorized",
    "summary": "Julie's boyfriend Ismaël lives with her; rather than worry about the time he spends with his colleague Alice, Julie invites Alice to join them. The three walk the streets of Paris, party, read, and sleep together. Sometimes it's lighthearted, sometimes there are jealousies. Then death strikes. In various ways, those left come to terms with the departure and absence of a loved one: showing concern, eating together, attempting new relationships, trying to \"be there\" for the other. Then, the spirit returns and new commitments are possible. The romantic elements of musical comedy play in contrast to the ambivalence of the lyrics and the story.",
    "ImageURL": "https://i.ytimg.com/vi/cxAUZZdpwnk/hq720.jpg?sqp=-oaymwEXCK4FEIIDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBhIrZd5O_9HJ0HfX7edSxnISn8tA",
    "imdb_id": "tt0996605",
    "imdb_rating": 7.2,
    "runtime": 91,
    "language": "English",
    "ytid": "s54vpKAFmS0"
  },
  {
    "Title": 89,
    "fulltitle": "89 (2017)",
    "movie_year": 2017,
    "Categories": "Uncategorized",
    "summary": "89 tells the incredible story of one of football's greatest triumphs: when against all odds Arsenal snatched the Championship title from Liverpool at Anfield in the last minute of the last game of the 1988/89 season. It's a universal tale of a band of brothers who, led by a charismatic and deeply respected manager, came together to defy the odds and create history. Mixing archive and previously unseen footage with revealing interviews, insights and memories from the original squad, game officials, famous fans and the people who were there on the night this is the definitive account of a watershed moment in football and a must-watch for any sports fan.",
    "ImageURL": "https://m.media-amazon.com/images/M/MV5BNjI0ZmE5NWEtMjlhYS00NjRiLTlmNWMtOTg5MTRmMWU4NDhhXkEyXkFqcGc@._V1_.jpg",
    "imdb_id": "tt7614404",
    "imdb_rating": 8.1,
    "runtime": 91,
    "language": "English",
    "ytid": "5hfAExhHTMM"
  },
  {
    "Title": "The Foster Boy",
    "fulltitle": "The Foster Boy (2011)",
    "movie_year": 2011,
    "Categories": "Drama",
    "summary": "The illegitimate orphan child, 12-year-old Max, is sold by the local minister for a basket of food to the Bösiger family, who own a mountain farm. Max' initial hope of finally finding a loving home is brutally shattered: The farmer and his wife treat Max like livestock, and their son Jacob humiliates and abuses him. Only the local teacher notices the child suffering on the farm.",
    "ImageURL": "https://play-lh.googleusercontent.com/proxy/r_k27Rqe3YtfwiuAm5QOQpfUbSSVCI_bzuRVzUvQd69dJI3i7WAa0pFBNSgG8T5W0uaZ0Z6Y3oIos1YfAE7JU6eDuphrWhRZrhawctTX0yKwQhZELbclxhdnK2LqprYGmavj87gfxzWCY6BuyfnwjaY8DzJovTFSJNZhIg=s3840-w3840-h2160",
    "imdb_id": "tt2057931",
    "imdb_rating": 7.4,
    "runtime": 107,
    "language": "English",
    "ytid": "E9Qv_XVJ-js"
  },
  {
    "Title": "Forever My Girl",
    "fulltitle": "Forever My Girl (2018)",
    "movie_year": 2018,
    "Categories": "Drama|Music|Romance",
    "summary": "After being gone for a decade a country star returns home to the love he left behind.",
    "ImageURL": "https://m.media-amazon.com/images/S/pv-target-images/a9b60763904cdb8b6a642868500a746f5aa5b8349e04b271627933e7426c006e.png",
    "imdb_id": "tt4103724",
    "imdb_rating": 6.4,
    "runtime": 108,
    "language": "English",
    "ytid": "3vqcMr1q5Uc"
  },
  {
    "Title": "Tom Segura: Disgraceful",
    "fulltitle": "Tom Segura: Disgraceful (2018)",
    "movie_year": 2018,
    "Categories": "Comedy|Documentary",
    "summary": "Comedian Tom Segura rants about funny things about pop culture and the way of living in 2018.",
    "ImageURL": "https://scrapsfromtheloft.com/wp-content/uploads/2025/12/Tom-Segura-Teacher.jpg",
    "imdb_id": "tt7379330",
    "imdb_rating": 7.5,
    "runtime": 0,
    "language": "English",
    "ytid": "kYYINJM3lPA"
  },
  {
    "Title": "The Secret Rules of Modern Living: Algorithms",
    "fulltitle": "The Secret Rules of Modern Living: Algorithms (2015)",
    "movie_year": 2015,
    "Categories": "Documentary",
    "summary": "Professor Marcus du Sautoy demystifies the hidden world of algorithms and reveals where these 2,000-year-old problem solvers came from, how they work, and what they have achieved.",
    "ImageURL": "https://m.media-amazon.com/images/S/pv-target-images/e88f8463a3e7e1d6c47393450144c9411a0578af65098820980c1b513f7c3204.jpg",
    "imdb_id": "tt5818010",
    "imdb_rating": 7.5,
    "runtime": 58,
    "language": "English",
    "ytid": "hpyxmT6KSvw"
  },
  {
    "Title": "Secrets in the Fall",
    "fulltitle": "Secrets in the Fall (2015)",
    "movie_year": 2015,
    "Categories": "Family",
    "summary": "Nothing is impossible for a group of young campers, friends and enemies alike, on a weekend retreat at Camp Pinnacle. But what starts as an exciting wilderness adventure turns into trouble when a young camper goes missing and the rest of the group must set out to find him. The campers are forced to overcome their differences and band together to re-claim their weekend and make it out of the woods before dark!",
    "ImageURL": "https://lh3.googleusercontent.com/9wfwYxolME_S2iZu92QBeTNFs9Aq4PyLg6IWyomhcKp_cxjlYrW2oHjocrIssrShVT9JtlLphNgFBg",
    "imdb_id": "tt2522908",
    "imdb_rating": 7.3,
    "runtime": 0,
    "language": "English",
    "ytid": "eMVw1pHVMAw"
  },
  {
    "Title": "Silent Night",
    "fulltitle": "Silent Night (2017)",
    "movie_year": 2017,
    "Categories": "Comedy|Drama",
    "summary": "Adam unexpectedly visits his family house at Christmas after a few years of working abroad. No family member knows about his secret plans and the real reasons of his visit.",
    "ImageURL": "https://www.catholicherald.com/wp-content/uploads/2022/01/AdobeStock_301105728-christmas-nativity-manger-scene-crop.jpg.webp",
    "imdb_id": "tt7133554",
    "imdb_rating": 7.5,
    "runtime": 100,
    "language": "English",
    "ytid": "cA6BUYVkQoE"
  },
  {
    "Title": "Suicide Squad: Hell to Pay",
    "fulltitle": "Suicide Squad: Hell to Pay (2018)",
    "movie_year": 2018,
    "Categories": "Action|Animation",
    "summary": "Task Force X targets a powerful mystical object that they will risk their lives to steal.",
    "ImageURL": "https://resizing.flixster.com/Pl-JLNKaQbkUino3Jr9COVkIMZs=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p15101072_i_h10_aa.jpg",
    "imdb_id": "tt7167602",
    "imdb_rating": 7.2,
    "runtime": 86,
    "language": "English",
    "ytid": "EPZZvk-wbGE"
  },
  {
    "Title": "Wildling",
    "fulltitle": "Wildling (2018)",
    "movie_year": 2018,
    "Categories": "Fantasy|Horror",
    "summary": "Anna spends her entire childhood under the care of a mysterious man she only knows as Daddy. He keeps her locked in an attic making her fear the Wildling, a child-eating monster that roams the outside. At age 16, Anna is freed by small-town sheriff Ellen Cooper who helps her start a new life as a normal teenager. But as Anna's body begins to blossom, her childhood nightmares return with a vengeance, leading to the conclusion of a terrifying secret.",
    "ImageURL": "https://www.filminquiry.com/wp-content/uploads/2018/04/Wildling-Feature-1024x683.jpg",
    "imdb_id": "tt5085924",
    "imdb_rating": 6.1,
    "runtime": 92,
    "language": "English",
    "ytid": "eyl1Wf90AgY"
  },
  {
    "Title": "The Humanity Bureau",
    "fulltitle": "The Humanity Bureau (2017)",
    "movie_year": 2017,
    "Categories": "Action|Sci-Fi",
    "summary": "A dystopian thriller set in the year 2030 that sees the world in a permanent state of economic recession and facing serious environmental problems as a result of global warming.",
    "ImageURL": "https://m.media-amazon.com/images/S/pv-target-images/868c34cc96ca81e4aba26e128e86c78e34cbce2a5acadb3dbc6e7894375f25a0.jpg",
    "imdb_id": "tt6143568",
    "imdb_rating": 6.1,
    "runtime": 95,
    "language": "English",
    "ytid": "kUH8JGhRzPY"
  },
  {
    "Title": "Farewell Ferris Wheel",
    "fulltitle": "Farewell Ferris Wheel (2016)",
    "movie_year": 2016,
    "Categories": "Documentary|Drama|News",
    "summary": "Farewell, Ferris Wheel examines the link between America's carnival industry and a small Mexican town that legally provides one third of the carnival's labor. However, increased regulations are compromising this longstanding connection, putting both the industry and its workers in jeopardy.",
    "ImageURL": "https://m.media-amazon.com/images/S/pv-target-images/b479141f2f4599ae551d7af97f75d7e9690a34df26c259e928f6b81e223c53d1.jpg",
    "imdb_id": "tt2349677",
    "imdb_rating": 7.4,
    "runtime": 72,
    "language": "English",
    "ytid": "-K2m6AKNB-g"
  },
  {
    "Title": "Don't Talk to Irene",
    "fulltitle": "Don't Talk to Irene (2017)",
    "movie_year": 2017,
    "Categories": "Comedy",
    "summary": "Irene must endure 2 weeks of community service at a retirement home. Following her passion for cheerleading, she secretly signs up the senior residents to audition for a dance-themed reality show to prove that you don't need to be physically \"perfect\" to be perfectly AWESOME.",
    "ImageURL": "https://img.kanopy.com/cdn-cgi/image/fit=cover,height=540,width=960/https://static-assets.kanopy.com/video-images/fa58a4ce-50ad-4f02-be1e-b954dccea206.jpg",
    "imdb_id": "tt5030452",
    "imdb_rating": 6.4,
    "runtime": 90,
    "language": "English",
    "ytid": "lK48UxWuUho"
  },
  {
    "Title": "Blood Road",
    "fulltitle": "Blood Road (2017)",
    "movie_year": 2017,
    "Categories": "Documentary|History|Sport",
    "summary": "The mysteries surrounding her father's death in the Vietnam war lead ultra-endurance mountain biker Rebecca Rusch on an emotional journey as she pedals 1200 miles of the Ho Chi Minh trail.",
    "ImageURL": "https://m.media-amazon.com/images/M/MV5BYjA3ZWNlZmItM2UxNC00OGY0LTlmNzUtMjFjZDdmNjY0MTZmXkEyXkFqcGc@._V1_.jpg",
    "imdb_id": "tt6900092",
    "imdb_rating": 6.9,
    "runtime": 96,
    "language": "English",
    "ytid": "XCzVqiN950M"
  },
  {
    "Title": "Andre the Giant",
    "fulltitle": "Andre the Giant (2018)",
    "movie_year": 2018,
    "Categories": "Documentary",
    "summary": "A look at the life and career of professional wrestler André Roussimoff, who gained notoriety in the 1980s as Andre the Giant.",
    "ImageURL": "https://www.wwe.com/f/styles/wwe_16_9_xl/public/2017/05/61_SNME_10311985_0034-198240076--b0ec133d158aee2c8949a8be5c21bc4e.jpg",
    "imdb_id": "tt6543420",
    "imdb_rating": 8.2,
    "runtime": 85,
    "language": "English",
    "ytid": "f_jTeuajas0"
  },
  {
    "Title": "Dead on Arrival",
    "fulltitle": "Dead on Arrival (2017)",
    "movie_year": 2017,
    "Categories": "Thriller",
    "summary": "A pharmaceutical sales rep visits a small town in Louisiana on business. He finds himself in a dark world of corruption and murder with 24 hours to live, running from the police, the mob and a sheriff that wants him dead.",
    "ImageURL": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2405340/23f926aeb91de1bf56bf8176fb2da6d1c4d2379a/capsule_616x353.jpg?t=1767339597",
    "imdb_id": "tt5903088",
    "imdb_rating": 6.9,
    "runtime": 97,
    "language": "English",
    "ytid": "8jJ-kC-rq0Q"
  },
  {
    "Title": "Big Time",
    "fulltitle": "Big Time (2017)",
    "movie_year": 2017,
    "Categories": "Documentary",
    "summary": "Bjarke Ingels started out as a young man dreaming of creating cartoons. Now, he has been named \"one of architecture's biggest innovators\" by The Wall Street Journal and one of The 100 Most Influential People on the planet by TIME Magazine. BIG TIME follows Bjarke during the course of 7 years (2009-2016), while he struggles to finish his biggest project so far. We are let into Bjarke's creative processes as well as the endless compromises that his work entails, and we are on the side when his personal life starts putting pressure on him, too. In addition to the recently opened architectural marvel VIA 57 West (625 West 57th Street), Bjarke Ingels' company Bjarke Ingels Group (BIG) was given the task of designing and building one of the skyscrapers which will replace Two World Trade Center in Manhattan. While Bjarke is creating these buildings, which will change the New York skyline, he is hit by health-related issues. The Film offers an intimate look into the innovative and ambitious ...",
    "ImageURL": "https://playtoearn.com/img/dapp/big-time/big-time_e02775b5afe85b89e92041149ef9c6d2_5546695cd6b172aac5abcfb754d6ea50.jpg",
    "imdb_id": "tt7630164",
    "imdb_rating": 6.2,
    "runtime": 93,
    "language": "English",
    "ytid": "VK0mGdMKMW4"
  },
  {
    "Title": "Adventures in Babysitting",
    "fulltitle": "Adventures in Babysitting (2016)",
    "movie_year": 2016,
    "Categories": "Adventure|Comedy|Family",
    "summary": "Two teen rival babysitters, Jenny and Lola, team up to hunt down one of their kids who accidentally runs away into the big city without any supervision.",
    "ImageURL": "https://images.ctfassets.net/m3qyzuwrf176/3NwJVDYCNE3BMIxUBYDU79/76751e33aad1edb33f6cc785006d8adb/_Jun22_ADVENTURES_IN_BABYSITTING_Teen1.jpg?fm=webp&w=1000",
    "imdb_id": "tt4456850",
    "imdb_rating": 6.1,
    "runtime": 105,
    "language": "English",
    "ytid": "BbTTXUMVTTU"
  },
  {
    "Title": "Banana in a Nutshell",
    "fulltitle": "Banana in a Nutshell (2005)",
    "movie_year": 2005,
    "Categories": "Documentary",
    "summary": "An intimate portrait of a Chinese-European couple in New Zealand, and their journey to get a blessing for marriage from traditional Chinese parents.",
    "ImageURL": "https://www.nziff.co.nz/assets/sm/upload/oc/qt/8x/ty/banana.still.steve_roseNutshell.jpg?k=bd2321b5e9",
    "imdb_id": "tt1537196",
    "imdb_rating": 6.6,
    "runtime": 0,
    "language": "English",
    "ytid": "6vgD78Z6ut4"
  },
  {
    "Title": "Hostiles",
    "fulltitle": "Hostiles (2017)",
    "movie_year": 2017,
    "Categories": "Adventure|Drama|Western",
    "summary": "In 1892, after nearly two decades of fighting the Cheyenne, the Apache, and the Comanche natives, the United States Cavalry Captain and war hero, Joseph Blocker, is ordered to escort the ailing Cheyenne chief, Yellow Hawk--his most despised enemy--to his ancestral home in Montana's Valley of the Bears. Nauseated with a baleful anger, Joseph's unwelcome final assignment in the feral American landscape is further complicated, when the widowed settler, Rosalie Quaid, is taken in by the band of soldiers, as aggressive packs of marauding Comanches who are still on the warpath, are thirsty for blood. In a territory crawling with hostiles, can the seasoned Captain do his duty one last time?",
    "ImageURL": "https://occ-0-8407-2218.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABZrZp4mepIOHDAissyMWyxkkEFW0ZSrBQrOXm4X3V0CwXb45Xb1h24UyPtnI2ZGbpJzEs3xyc89g2n7GEBNsqlA5hvySDo5YA_mh.jpg?r=f53",
    "imdb_id": "tt5478478",
    "imdb_rating": 7.3,
    "runtime": 134,
    "language": "English",
    "ytid": "1M5cj4UmscE"
  },
  {
    "Title": "Maze Runner: The Death Cure",
    "fulltitle": "Maze Runner: The Death Cure (2018)",
    "movie_year": 2018,
    "Categories": "Action|Sci-Fi|Thriller",
    "summary": "In the epic finale to The Maze Runner Saga, Thomas leads his group of escaped Gladers on their final and most dangerous mission yet. To save their friends, they must break into the legendary last city, a WCKD controlled labyrinth that may turn out to be the deadliest maze of all. Anyone who makes it out alive will get the answers to the questions the Gladers have been asking since they first arrived in the maze. Will Thomas and the crew make it out alive? Or will Ava Paige get her way?",
    "ImageURL": "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/2c4d76fd-db99-4f55-be9c-93713a84fe98/compose?aspectRatio=1.78&format=webp&width=1200",
    "imdb_id": "tt4500922",
    "imdb_rating": 6.5,
    "runtime": 141,
    "language": "English",
    "ytid": "wnE_y4vN9nQ"
  },
  {
    "Title": "Den of Thieves",
    "fulltitle": "Den of Thieves (2018)",
    "movie_year": 2018,
    "Categories": "Action|Crime|Drama|Mystery|Thriller",
    "summary": "A gritty L.A crime saga which follows the intersecting and often personally connected lives of an elite unit of the LA County Sheriff's Dept. and the state's most successful bank robbery crew as the outlaws plan a seemingly impossible heist on the Federal Reserve Bank of downtown Los Angeles.",
    "ImageURL": "https://www.hollywoodreporter.com/wp-content/uploads/2018/01/den-of-thieves-018_dot_unit_11123rc_rgb-h_2018.jpg?w=1296&h=730&crop=1",
    "imdb_id": "tt1259528",
    "imdb_rating": 7,
    "runtime": 140,
    "language": "English",
    "ytid": "FKd_ks0rdAM"
  },
  {
    "Title": "V.I.P.",
    "fulltitle": "V.I.P. (2017)",
    "movie_year": 2017,
    "Categories": "Action|Crime|Thriller",
    "summary": "The son (Lee Jong-Suk) of a high-ranking North Korean official is suspected of committing serial murders around the world. To stop the killer, South Korea, North Korea and Interpol chase after him.",
    "ImageURL": "https://img.freepik.com/free-photo/vip-typography-3d-golden-font_53876-104193.jpg?semt=ais_hybrid&w=740&q=80",
    "imdb_id": "tt6413410",
    "imdb_rating": 6.4,
    "runtime": 128,
    "language": "English",
    "ytid": "dwRkl2BjtGQ"
  },
  {
    "Title": "Walk Hard: The Dewey Cox Story",
    "fulltitle": "Walk Hard: The Dewey Cox Story (2007)",
    "movie_year": 2007,
    "Categories": "Comedy|Music",
    "summary": "The up-and-down-and-up-again story of musician Dewey Cox, whose songs would change a nation. On his rock 'n roll spiral, Cox sleeps with 411 women, marries three times, has 36 kids, stars in his own 70s TV show, collects friends ranging from Elvis to the Beatles to a chimp, and gets addicted to - and then kicks - every drug known to man; but despite it all, Cox grows into a national icon and eventually earns the love of a good woman - longtime backup singer Darlene.",
    "ImageURL": "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/ed522e04-1a4e-4366-9bc7-623a0ce9c69c/55eb2c18-20f4-11f0-adbd-0250a7dc3367?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=500",
    "imdb_id": "tt0841046",
    "imdb_rating": 6.8,
    "runtime": 96,
    "language": "English",
    "ytid": "4yzjtnj8Y3U"
  },
  {
    "Title": "Freaky Friday",
    "fulltitle": "Freaky Friday (2003)",
    "movie_year": 2003,
    "Categories": "Comedy|Family|Fantasy|Music|Romance",
    "summary": "The wide generation gap between Tess Coleman and her teenage daughter Anna is more than evident. They simply cannot understand each other's preferences. On a Thursday night they have a big argument in a Chinese restaurant. Both receive a fortune cookie each from the restaurant owner's mother which causes them to switch bodies next day. As they adjust with their new personalities, they begin to understand each other more and eventually it's the mutual self-respect that sorts the things out.",
    "ImageURL": "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/19b84cde-80d3-46bd-819d-2e9c99931485/compose?aspectRatio=1.78&format=webp&width=1200",
    "imdb_id": "tt0322330",
    "imdb_rating": 6.2,
    "runtime": 97,
    "language": "English",
    "ytid": "obOyYTto5Sg"
  },
  {
    "Title": "Perfect Strangers",
    "fulltitle": "Perfect Strangers (2017)",
    "movie_year": 2017,
    "Categories": "Comedy",
    "summary": "In the same night that happens a blood red moon, some longtime friends reunite to dinner: the group is formed by plastic surgeon Alfonso and his wife, psychologist Eva, who are the hosts of the dinner; lawyers Antonio and his wife Ana; taxi driver Eduardo and his young and recent wife, veterinary Blanca; and finally Pepe, a former gym teacher actually unemployed, who surprisingly appears without Lucía, his recent girlfriend. Motivated by Blanca, who have some suspects about the group by the behaviors of some of them, she proposes a game where all diners leave their cell phones on the table, at the condition to say to everyone the contents of all text and voice messages. Starting like an innocent game, the progressive revelation of secrets as they appear cause a series the events each time more dramatics: Alfonso suspects that Eva has an affair, Ana thinks wrongly that Antonio is homosexual, Blanca realizes a horrible side about her marriage with Eduardo, and Pepe tries to keep hidden ...",
    "ImageURL": "https://m.media-amazon.com/images/S/pv-target-images/42365319467ec6b062b55dac05fadb2b06c6f20c31838a9e21e4dd4ed0b90e5d.jpg",
    "imdb_id": "tt6101820",
    "imdb_rating": 7,
    "runtime": 97,
    "language": "English",
    "ytid": "-lOUnBsjGuY"
  },
  {
    "Title": "Paterno",
    "fulltitle": "Paterno (2018)",
    "movie_year": 2018,
    "Categories": "Biography|Drama",
    "summary": "The film centers on Joe Paterno, who, after becoming the winningest coach in college football history, is embroiled in Penn State's Jerry Sandusky sexual abuse scandal, challenging his legacy and forcing him to face questions of institutional failure regarding the victims.",
    "ImageURL": "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/cd57eb76-5302-4bdc-86f6-749e214a2417/5fc0f25b-fef0-4095-8843-a54a324f6447?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=500",
    "imdb_id": "tt2388986",
    "imdb_rating": 6.6,
    "runtime": 105,
    "language": "English",
    "ytid": "scI7dYdlzuY"
  },
  {
    "Title": "Shirley: Visions of Reality",
    "fulltitle": "Shirley: Visions of Reality (2013)",
    "movie_year": 2013,
    "Categories": "Documentary",
    "summary": "13 of Edward Hopper's paintings are brought alive by the film, telling the story of a woman, whose thoughts, emotions and contemplations let us observe an era in American history. Shirley is a woman in America in the 1930s, '40s, '50s, and early '60s. A woman who would like to influence the course of history with her professional and socio political involvement.",
    "ImageURL": "https://cinema-austriaco.org/wp-content/uploads/2019/07/shirley-visions-of-reality-2013-deutsch-recensione.jpg",
    "imdb_id": "tt2636806",
    "imdb_rating": 6.5,
    "runtime": 92,
    "language": "English",
    "ytid": "rcQ4JKxxukY"
  },
  {
    "Title": "5 Centimeters Per Second",
    "fulltitle": "5 Centimeters Per Second (2007)",
    "movie_year": 2007,
    "Categories": "Animation|Drama|Romance",
    "summary": "Takaki and Akari are two classmates in elementary school. During their time together they have become close friends. Their relationship is tested when Akari moves to another city because of her parents' jobs. Both of them struggle to keep their friendship alive, as time and distance slowly pulls them apart. When Takaki finds out that he is moving further away, he decides to visit Akari one last time.",
    "ImageURL": "https://static0.cbrimages.com/wordpress/wp-content/uploads/2024/09/5-centimeters-per-second.jpg?w=1200&h=900&fit=crop",
    "imdb_id": "tt0983213",
    "imdb_rating": 7.7,
    "runtime": 63,
    "language": "English",
    "ytid": "SzAO_NeCmkM"
  },
  {
    "Title": "Faces Places",
    "fulltitle": "Faces Places (2017)",
    "movie_year": 2017,
    "Categories": "Documentary",
    "summary": "Agnes Varda, one of the leading lights of France's honored French New Wave cinema era, and professional photographer and muralist, J.R., partake on a special art project. Together, they travel around France in a special box truck equipped as a portable photo booth and traveling printing facility as they take photographs of people around the country. With that inspiration, they also create special colossal mural pictures of individuals, communities and places they want to honor and celebrate. Along the way, the old cinematic veteran and the young artistic idealist enjoy an odd friendship as they chat and explore their views on the world as only they can.",
    "ImageURL": "https://assets.mubicdn.net/images/film/170199/image-w1280.jpg?1745493724",
    "imdb_id": "tt5598102",
    "imdb_rating": 8,
    "runtime": 89,
    "language": "English",
    "ytid": "2rKZcAiLHlY"
  },
  {
    "Title": "The Post",
    "fulltitle": "The Post (2017)",
    "movie_year": 2017,
    "Categories": "Biography|Drama|History|Thriller",
    "summary": "When American military analyst, Daniel Ellsberg, realizes to his disgust the depths of the US government's deceptions about the futility of the Vietnam War, he takes action by copying top-secret documents that would become the Pentagon Papers. Later, Washington Post owner, Kay Graham, is still adjusting to taking over her late husband's business when editor Ben Bradlee discovers the New York Times has scooped them with an explosive expose on those papers. Determined to compete, Post reporters find Ellsberg himself and a complete copy of those papers. However, the Post's plans to publish their findings are put in jeopardy with a Federal restraining order that could get them all indicted for Contempt. Now, Kay Graham must decide whether to back down for the safety of her paper or publish and fight for the Freedom of the Press. In doing so, Graham and her staff join a fight that would have America's democratic ideals in the balance.",
    "ImageURL": "https://variety.com/wp-content/uploads/2016/02/the-post-2.jpg",
    "imdb_id": "tt6294822",
    "imdb_rating": 7.2,
    "runtime": 116,
    "language": "English",
    "ytid": "nrXlY6gzTTM"
  },
  {
    "Title": "The Anthem of the Heart",
    "fulltitle": "The Anthem of the Heart (2017)",
    "movie_year": 2017,
    "Categories": "Drama|Family",
    "summary": "Takumi is on his class' community outreach group. His teacher assigns more students to the group including a student who, due to a mishap, has foregone speaking. The class has to perform a musical, but volunteers brave enough to perform are hard to come by. The reluctance slowly begins to wash away when the aforementioned girl makes an effort to perform. As the day of the performance approaches will the students be able to overcome their reluctance and go for it?",
    "ImageURL": "https://anthemoftheheart.com/assets/img/bluray/jacket_box_sample.jpg",
    "imdb_id": "tt6738046",
    "imdb_rating": 6.2,
    "runtime": 119,
    "language": "English",
    "ytid": "EnbgMjdguxI"
  },
];